{% set name = "xtensor" %}
{% set version = "0.15.9" %}
{% set sha256 = "2a2386f526c3c5fdfeda43515c68e503ff237e55cdb5c6f43db0161e2ee19a56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py<35]

requirements:
  build:
    - toolchain
    - cmake
    - xtl >=0.4.1,<0.5
  run:
    - xtl >=0.4.1,<0.5

test:
  commands:
    - test -d ${PREFIX}/include/xtensor  # [unix]
    - test -f ${PREFIX}/include/xtensor/xarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor/xtensorConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor/xtensorConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor\xarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensorConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensorConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
